# fly.toml app configuration file generated for bsky-deletions on 2024-09-26T00:26:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bsky-deletions'
primary_region = 'ewr'

[build]

[mounts]
  source = "bsky_deletions_cache"
  destination = "/data"
  initial_size = "10gb"

[metrics]
  port = 3000
  path = "/metrics"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests" # skeptical with ws but let's see
    soft_limit = 500

[[http_service.checks]]
  grace_period = "8s"
  interval = "15s"
  method = "GET"
  timeout = "2s"
  path = "/ready"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
